#!/bin/env sh

iDIR="$HOME/.config/mako/icons"

if [ "$#" -eq 1 ]; then
    case "$1" in
        "-d")
            brightnessctl set 2%-
            ;;
        "-i")
            brightnessctl set 2%+
            ;;
        * )
            echo "Not a valid option. Choose either -d or -i"
    esac
    backlight="$(brightnessctl -m | awk -F, '{print $4}')"
    brightlvl="${backlight%%%}"

# Get icons
    if [ "$brightlvl" -eq 0 ]; then
            echo "$iDIR/volume-mute.png"
    elif [ "$brightlvl" -le 30 ]; then
            echo "$iDIR/volume-low.png"
    elif [ "$brightlvl" -le 60 ]; then
            echo "$iDIR/volume-mid.png"
    elif [ "$brightlvl" -le 100 ]; then
            echo "$iDIR/volume-high.png"
    fi

    notify-send -h string:x-canonical-private-synchronous:sys-bright -h "int:value:$brightlvl" -u low -i "$(get_icon)" "Backlight" "Brightness: $backlight"
else
    echo "Too many or not enough arguments"
fi
