#!/bin/env sh
if [ "$#" -eq 1 ]; then
    file="$1"
    filename="$(echo $file | sed 's:.*/::')";
#    wpg -a "${file}";
    wal -i "${file}";
#    wpg -A "${filename}";
#    wpg -s "${filename}";
fi
