#!/bin/env sh

################
# shell aliases #
################
alias FUCK='sudo $(fc -ln -1)'
alias dotgit="git --git-dir=$HOME/.dotfiles --work-tree=$HOME"

###################
# FILE MANAGEMENT #
###################
# Quick ls
alias dir="dir --color=auto"
alias vdir="vdir --color=auto --group-directories-first -ahF"
alias l="ls --color=auto -F"
alias la="l -a"
# Quick cd
alias cdh="cd $HOME"
alias cdr="cd /"
alias cdconf="cd $HOME/.config"
alias cdsd="cd /etc/systemd/system"
alias cde="cd /etc"
alias ..="cd .."
alias ...="cd .. ; cd .."
alias ....="cd .. ; cd .. ; cd .."


# Quit
alias q="exit"
alias sys="systemctl"
alias sysusr="systemctl --user"

##########
# PACMAN #
##########
    # alias pacsyu='pacman -Syu'
    # alias paclean='pacman -Scc'
    # alias pacins='pacman -S'
    # alias pacrm='pacman -Rscn'

#############
# COMPILING #
#############
## GROFF
    # # Quick ps to png
    # alias ps2png="gs -dNOPAUSE -dBATCH -sDEVICE=png16m -r120x120 -sOutputFile='ps-%d.png'"
    # # Quick ms to ps
    # alias gmsps="groff -m ms -T ps"
